openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BU-COVID/COVID-Registry/1.0.0
info:
  description: This is the API for the BU-COVID Registry
  version: "1.0.0"
  title: COVID Key Registry
  
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: medicalProfessionals
    description: calls available to medical professionals
  - name: developers
    description: Operations available to regular developers
paths:
  /ContactCheck:
    post:
      tags:
        - developers
      operationId: serverSideCompare
      description: User uploads the keys they have seen and receives a response telling them whether or not they have come into contact with a key in the database. This is only used in the case that server side comparisons are desired
      responses:
        '210':
          description: Key match found
        '211':
          description: No key match found  

      
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/serverSideContactCheck"
    get:
      parameters:
        - in: path
          name: authentication
          schema:
            type: string
          required: true
          description: The authentication token of the user to get
      
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                type: string
                example: "BloomFilter in a string representation"
        '401':
          description: Unauthorized user

              
  /UploadCredentials:
    post:
      tags:
        - admins
      operationId: issueUploadKey
      description: Issue a new upload key to be used by medical professionals
      responses:
        '201':
          description: Key correctly generated
          content:
            application/json:
              schema:
                type: string
                example: "Generated Authorization String Here"
      
      requestBody:
        content:
          application/json:
            schema:
              type: string
              example: "Authorization String Here"
    delete:
      tags:
        - admins
      operationId: revokeUploadKey
      description: revoke a previously issued upload key
      
      responses:
        '201':
          description: Key has been successfully revoked
        '400':
          description: Bad input detected
        '401':
          description: Unauthorized user
        '404':
          description: key does not exist
              
  /InfectedKey:
    post:
      tags:
        - medicalProfessionals
      operationId: addKeys
      description: Adds an item to the system
      responses:
        '201':
          description: Key correctly generated
        '400':
          description: "invalid input, object invalid"

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/infectedData"
        description: Medical professional authorization and keys to be uploaded

components:
  schemas:
    key-data:
      type: object
      required:
        - key
        - time
      properties:
        key:
          type: string
          example: "Key Here"

        time:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
          
    serverSideContactCheck:
      type: object
      required:
        - authorization
        - seenKeys
      
      properties:
        authorization:
          type: string
          example: "Authorization String Here"
        seenKeys:
          type: array
          items:
            $ref: "#/components/schemas/key-data"
          
    infectedData:
      type: object
      required:
        - authorization
        - uploadKeys
      
      properties:
        authorization:
          type: string
          example: "Authorization String Here"
        upload-keys:
          type: array
          items:
            $ref: "#/components/schemas/key-data"
